Added exit status checks for download of tar.gz files, merging, and final SCE creation so process stops upon failure.

diff --git a/usr/bin/deb2sce b/usr/bin/deb2sce
--- a/usr/bin/deb2sce
+++ b/usr/bin/deb2sce
@@ -394,17 +394,34 @@ for DEBINFO in `ls -t /tmp/work`; do
 				if [ `/bb/md5sum "${DEBINFO}".tar.gz | cut -f1 -d" "` != `grep "^$DEBINFO": /tmp/PREBUILTMD5SUMLIST | cut -f2 -d" "` ]; then
 					echo "Fetching updated "${DEBINFO}".tar.gz.."
 					rm "${DEBINFO}".tar.gz*
-					/bb/wget -O "${DEBINFO}".tar.gz "$PREBUILTMIRROR"/"${DEBINFO}".tar.gz
+					/bb/wget -O "${DEBINFO}".tar.gz "$PREBUILTMIRROR"/"${DEBINFO}".tar.gz 
+					if [ "$?" != 0 ]
+					then
+						echo "failed on download of "${DEBINFO}".tar.gz"
+						cleanup
+						exit 1
+					fi
 				fi
 				
 			else
 				/bb/wget -O "${DEBINFO}".tar.gz "$PREBUILTMIRROR"/"${DEBINFO}".tar.gz 
+				if [ "$?" != 0 ]
+				then
+					echo "failed on download of "${DEBINFO}".tar.gz"
+					cleanup
+					exit 1
+				fi
 			fi
 	
 			if [ -f "${DEBINFO}".tar.gz ] && [ `/bb/md5sum "${DEBINFO}".tar.gz | cut -f1 -d" "` == `grep "^$DEBINFO": /tmp/PREBUILTMD5SUMLIST | cut -f2 -d" "` ]; then	 
 				echo "${DEBINFO}: `/bb/md5sum "${DEBINFO}".tar.gz | cut -f1 -d" "`" >> "$IMPORT"/"$TARGET"/usr/local/sce/"$TARGET"/"$TARGET".md5sum		  
 				echo "Merging "${DEBINFO}":"
-	    	   		tar xf "${DEBINFO}".tar.gz -C "$IMPORT"/"$TARGET"        		  
+	    	   		tar xf "${DEBINFO}".tar.gz -C "$IMPORT"/"$TARGET" 
+				if [ "$?" != 0 ]
+				then
+					echo "failed merging of "${DEBINFO}".tar.gz"
+					echo "${DEBINFO}".tar.gz  >> /tmp/import.log
+				fi  		  
 			else 
 				echo "md5sum failed for "${DEBINFO}".tar.gz, exiting.."
 				cleanup
@@ -517,6 +534,9 @@ if [ -f "$TCEDIR"/sce/"$TARGET".sce ] && mount | grep " /tmp/tcloop/"$TARGET" " 
 		cd "$TCEDIR"/sce/update/
 		/bb/md5sum "$TARGET".sce > "$TARGET".sce.md5.txt	
 		cd "$IMPORT"
+	else
+		echo "Error creating "$TARGET".sce.  Exiting.."
+		exit 1
 	fi
 	
 else
@@ -525,6 +545,9 @@ else
 		cd "$TCEDIR"/sce/
 		/bb/md5sum "$TARGET".sce > "$TARGET".sce.md5.txt	
 		cd "$IMPORT"
+	else
+		echo "Error creating "$TARGET".sce.  Exiting.."
+		exit 1
 	fi
 fi
 
diff --git a/usr/bin/sce-update b/usr/bin/sce-update
--- a/usr/bin/sce-update
+++ b/usr/bin/sce-update
@@ -147,6 +147,10 @@ if [ "$UPDATEALL" == "TRUE" ]; then
 		if [ "$NONINTERACTIVE" == "TRUE" ]; then
 			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
 				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
+				if [ "$?" == "0" ]; then
+					echo "Error in updating "$I".  Exiting.."
+					exit 1
+				fi 
 				echo "$I" >> /tmp/importupdated
 			done
 			echo "Refer to /tmp/updateavailable for details of package updates."
@@ -163,6 +167,10 @@ if [ "$UPDATEALL" == "TRUE" ]; then
 			## Update all SCEs
 			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
 				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
+				if [ "$?" == "0" ]; then
+					echo "Error in updating "$I".  Exiting.."
+					exit 1
+				fi 
 				echo "$I" >> /tmp/importupdated
 			done
 		fi
@@ -208,6 +216,10 @@ elif [ -f update/"$UPDATETARGET".sce ]; then
 		if [ "$NONINTERACTIVE" == "TRUE" ]; then
 			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
 				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
+				if [ "$?" == "0" ]; then
+					echo "Error in updating "$I".  Exiting.."
+					exit 1
+				fi 
 				echo "$I" >> /tmp/importupdated
 			done
 			echo "Refer to /tmp/updateavailable for details of package updates."
@@ -224,6 +236,10 @@ elif [ -f update/"$UPDATETARGET".sce ]; then
 			## Update all SCEs
 			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
 				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
+				if [ "$?" == "0" ]; then
+					echo "Error in updating "$I".  Exiting.."
+					exit 1
+				fi 
 				echo "$I" >> /tmp/importupdated
 			done
 		fi
@@ -269,6 +285,10 @@ elif [ -f "$UPDATETARGET".sce ]; then
 		if [ "$NONINTERACTIVE" == "TRUE" ]; then
 			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
 				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
+				if [ "$?" == "0" ]; then
+					echo "Error in updating "$I".  Exiting.."
+					exit 1
+				fi 
 				echo "$I" >> /tmp/importupdated
 			done
 			echo "Refer to /tmp/updateavailable for details of package updates."
@@ -285,6 +305,10 @@ elif [ -f "$UPDATETARGET".sce ]; then
 			## Update all SCEs
 			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
 				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
+				if [ "$?" == "0" ]; then
+					echo "Error in updating "$I".  Exiting.."
+					exit 1
+				fi 
 				echo "$I" >> /tmp/importupdated
 			done
 		fi
@@ -359,6 +383,10 @@ You can choose more than one, and enter "q" for quit when you have completed you
 				done
 				for D in `echo "$DEPLIST"`; do
 					grep "^$D$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$D"
+					if [ "$?" == "0" ]; then
+						echo "Error in updating "$I".  Exiting.."
+						exit 1
+					fi 
 					echo "$D" >> /tmp/importupdated
 				done
 				echo "Refer to /tmp/updateavailable for package update details."
@@ -378,6 +406,10 @@ You can choose more than one, and enter "q" for quit when you have completed you
 				#done
 				for D in `echo "$DEPLIST"`; do
 					grep "^$D$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$D"
+					if [ "$?" == "0" ]; then
+						echo "Error in updating "$I".  Exiting.."
+						exit 1
+					fi 
 					echo "$D" >> /tmp/importupdated
 				done
 			fi
