Bugfixes and now using the dependency data obtained from scd-update for sce-import when it is run during an update session as to not have to fetch that data twice during update.

diff --git a/usr/bin/debGetSceDep b/usr/bin/debGetSceDep
--- a/usr/bin/debGetSceDep
+++ b/usr/bin/debGetSceDep
@@ -127,8 +127,9 @@ unset PKGEXISTS
 		  	sudo umount "$DIR1"
 		  	rmdir "$DIR1"
 		else 
-			echo "ERROR:  "$I".sce not found!"
-			exit 1
+			:
+			#echo "ERROR:  "$I".sce not found!"
+			#exit 1
 		fi
 	done
 fi
diff --git a/usr/bin/sce-import b/usr/bin/sce-import
--- a/usr/bin/sce-import
+++ b/usr/bin/sce-import
@@ -74,7 +74,9 @@ exit_tcnet() {
 [ -f /tmp/.prebuiltmd5sumlist ] && sudo rm /tmp/.prebuiltmd5sumlist
 [ -f /tmp/.pkgextrafilemd5sumlist ] && sudo rm /tmp/.pkgextrafilemd5sumlist
 [ -f /tmp/.blocked ] && sudo rm /tmp/.blocked
-[ -f /tmp/.scelisterror ] && sudo rm /tmp/.scelisterror
+[ -f /tmp/.pkglisterror ] && sudo rm /tmp/.pkglisterror
+[ -f /tmp/.pkgdeperror ] && sudo rm /tmp/.pkgdeperror
+[ -f /tmp/.nogetdeps ] && sudo rm /tmp/.nogetdeps
 
 read IMPORTMIRROR < /opt/tcemirror
 PREBUILTMIRROR="${IMPORTMIRROR%/}/dCore/"$BUILD"/import"
@@ -82,7 +84,7 @@ IMPORTMIRROR="${IMPORTMIRROR%/}/dCore/import"
 
 
 unset FLAGS PACKAGELIST
-while getopts drsbolknupcvz OPTION
+while getopts drsbolknupcvzy OPTION
 do
 	case ${OPTION} in
 		c) CHECKALL=TRUE ;;
@@ -98,6 +100,7 @@ do
 		l) PACKAGELIST=TRUE ;;
 		v) VIEWPKGS=TRUE ;;
 		z) NOCONFIG=TRUE ;;
+		y) NOGETDEPS=TRUE ;;
 		*) exit 1 ;;
 	esac
 done
@@ -138,34 +141,8 @@ tar xvf /tmp/deb2sce.tar.gz PREBUILTMD5SUMLIST >/dev/null 2>&1
 tar xvf /tmp/deb2sce.tar.gz KEEPDOC >/dev/null 2>&1
 cd "$HERE"
 
-# Determine if non-interactive mode is being used.
-if grep -i "^NONINTERACTIVE=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
-	touch /tmp/.importinteractive
-	echo "Using the -n option."
-elif [ "$NONINTERACTIVE" == "TRUE" ]; then
-	touch /tmp/.importinteractive
-	echo "Using the -n option."
-fi
 
-if grep -i "^PRESERVEDEBINXMODE=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
-	PRESERVEDEBINXMODE=TRUE
-	echo "Using the -p option."
-elif [ "$PRESERVEDEBINXMODE" == "TRUE" ]; then
-	PRESERVEDEBINXMODE=TRUE
-	echo "Using the -p option."
-else
-	UPDATEDEBINXMODE=TRUE
-	PRESERVEDEBINXMODE=FALSE
-fi
 
-if grep -i "^UPDATEDEBINXMODE=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
-	UPDATEDEBINXMODE=TRUE
-	PRESERVEDEBINXMODE=FALSE
-	echo "Using the -u option."
-elif [ "$UPDATEDEBINXMODE" == "TRUE" ]; then
-	PRESERVEDEBINXMODE=FALSE
-	echo "Using the -u option."
-fi
 
 
 if [ "$UPDATEDEBINXMODE" == "TRUE" ]; then
@@ -183,94 +160,26 @@ fi
 read DEBINX < /tmp/debinx
 DEBINX="/etc/sysconfig/tcedir/import/debinx/$DEBINX"
 
+# Intermal flag to use /tmp/work provided by sce-update.
+if [ "$NOGETDEPS" == "TRUE" ]; then
+	touch /tmp/.nogetdeps
+	echo "Using the -y option."
+fi
+
+# Determine if non-interactive mode is being used.
+if grep -i "^NONINTERACTIVE=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
+	touch /tmp/.importinteractive
+	echo "Using the -n option."
+elif [ "$NONINTERACTIVE" == "TRUE" ]; then
+	touch /tmp/.importinteractive
+	echo "Using the -n option."
+fi
+
 if grep -wq "^$TARGET$" /tmp/PKGEXCLUDELIST > /dev/null 2>&1; then
 	echo " "
 	echo "$TARGET is a blocked package.  Exiting.."
 	echo " "
 	exit 0
-fi
-
-checkexist() {
-  if sudo grep -q "^$1:" /tmp/PKGADDDEP; then
-	:
-  elif sudo grep "^$1:" /tmp/PKGPREBUILTDEP > /dev/null 2>&1; then
-	:
-  elif sudo grep "^Package: $1$" "$TCEDIR"/import/debinx/debinx.* > /dev/null 2>&1; then
-	:
-  elif sudo grep -q "^Package: $1$" "$DEBINX" > /dev/null 2>&1; then
-	:
-  else
-	echo "$1" >> /tmp/.scelisterror
-  fi
-}
-
-# Determine if .lst file is being used or list specified, copy to /tmp/.targetfile
-if [ "$PACKAGELIST" == "TRUE" ] || [ -f "$TCEDIR"/sce/"$1".sce.lst ]; then
-	if [ -f "$1" ]; then
-		TARGETFILE=`readlink -f "$1"`
-		for I in `cat "$TARGETFILE"`; do
-			checkexist "$I"
-		
-		done
-		if [ -s /tmp/.scelisterror ]; then
-			echo " "
-			cat /tmp/.scelisterror
-			echo " "
-			if [ ! -f /tmp/.importinteractive ]; then
-				echo "The above files in "$TARGETFILE" do not exist in dCore repos."
-				echo -n "Do you want to proceed anyway? (y/N):"
-				read ans
-				if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-					:
-				else
-					exit 1
-				fi
-			else
-				:
-			fi
-		fi
-		sudo cp $TARGETFILE /tmp/.targetfile
-		TARGET=`basename $1 .sce.lst`
-	elif [ -s "$TCEDIR"/sce/"$1".sce.lst ]; then
-		TARGETFILE="$TCEDIR"/sce/"$1".sce.lst
-		for I in `cat "$TARGETFILE"`; do
-			checkexist "$I"
-		done
-		if [ -s /tmp/.scelisterror ]; then
-			echo " "
-			cat /tmp/.scelisterror
-			echo " "
-			if [ ! -f /tmp/.importinteractive ]; then
-				echo "The above files in "$TARGETFILE" do not exist in dCore repos."
-				echo -n "Do you want to proceed anyway? (y/N):"
-				read ans
-				if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-					:
-				else
-					exit 1
-				fi
-			else
-				:
-			fi
-		fi
-		sudo cp "$TCEDIR"/sce/"$1".sce.lst /tmp/.targetfile
-	else
-		echo "Neither a file named "$1" nor does "$TCEDIR"/sce/"$1".sce.lst exist."
-		echo "Exiting.."
-		exit 1
-	fi
-fi
-
-
-
-# Determine if the -d option or the existence of a dep file
-# is present and use dep file if found.
-if [ "$DEPS" == "TRUE" ]; then
-	touch /tmp/.importdep
-	echo "Using the -d option."
-elif ls /etc/sysconfig/tcedir/sce/"$TARGET".sce.dep > /dev/null 2>&1; then
-	touch /tmp/.importdep
-	echo "Existing dep file found."
 fi
 
 # Determine if the size option is being used.
@@ -319,6 +228,128 @@ fi
 
 
 
+checklist() {
+  if sudo grep -q "^$1:" /tmp/PKGADDDEP; then
+	:
+  elif sudo grep "^$1:" /tmp/PKGPREBUILTDEP > /dev/null 2>&1; then
+	:
+  elif sudo grep "^Package: $1$" "$TCEDIR"/import/debinx/debinx.* > /dev/null 2>&1; then
+	:
+  elif sudo grep -q "^Package: $1$" "$DEBINX" > /dev/null 2>&1; then
+	:
+  else
+	echo "$1" >> /tmp/.pkglisterror
+  fi
+}
+
+
+checkdep() {
+  if sudo grep -q "^$1:" /tmp/PKGADDDEP; then
+	:
+  elif sudo grep "^$1:" /tmp/PKGPREBUILTDEP > /dev/null 2>&1; then
+	:
+  elif sudo grep "^Package: $1$" "$TCEDIR"/import/debinx/debinx.* > /dev/null 2>&1; then
+	:
+  elif sudo grep -q "^Package: $1$" "$DEBINX" > /dev/null 2>&1; then
+	:
+  else
+	echo "$1" >> /tmp/.pkgdeperror
+  fi
+}
+
+# Determine if .lst file is being used or list specified, copy to /tmp/.targetfile
+if [ "$PACKAGELIST" == "TRUE" ] || [ -f "$TCEDIR"/sce/"$1".sce.lst ]; then
+	if [ -f "$1" ] && [ "$PACKAGELIST" == "TRUE" ]; then
+		TARGETFILE=`readlink -f "$1"`
+		for I in `cat "$TARGETFILE"`; do
+			checklist "$I"
+		done
+		if [ -s /tmp/.pkglisterror ]; then
+			echo " "
+			cat /tmp/.pkglisterror
+			echo " "
+			if [ ! -f /tmp/.importinteractive ]; then
+				echo "The above files in "$TARGETFILE" do not exist in dCore repos."
+				echo -n "Do you want to proceed anyway? (y/N):"
+				read ans
+				if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+					:
+				else
+					exit 1
+				fi
+			else
+				echo "The above files in "$TARGETFILE" do not exist in dCore repos."
+			fi
+		fi
+		sudo cp $TARGETFILE /tmp/.targetfile
+		TARGET=`basename $1 .sce.lst`
+	elif [ -s "$TCEDIR"/sce/"$1".sce.lst ]; then
+		echo "Existing list file found."
+		TARGETFILE=""$TCEDIR"/sce/"$1".sce.lst"
+		for I in `cat "$TARGETFILE"`; do
+			checklist "$I"
+		done
+		if [ -s /tmp/.pkglisterror ]; then
+			echo " "
+			cat /tmp/.pkglisterror
+			echo " "
+			if [ ! -f /tmp/.importinteractive ]; then
+				echo "The above files in "$TARGETFILE" do not exist in dCore repos."
+				echo -n "Do you want to proceed anyway? (y/N):"
+				read ans
+				if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+					:
+				else
+					exit 1
+				fi
+			else
+				echo "The above files in "$TARGETFILE" do not exist in dCore repos."
+			fi
+		fi
+		sudo cp "$TCEDIR"/sce/"$1".sce.lst /tmp/.targetfile
+	else
+		echo "Neither a file named "$1" nor does "$TCEDIR"/sce/"$1".sce.lst exist."
+		echo "Exiting.."
+		exit 0
+	fi
+fi
+
+
+
+# Determine if the -d option or the existence of a dep file
+# is present and use dep file if found.
+if [ "$DEPS" == "TRUE" ]; then
+	touch /tmp/.importdep
+	echo "Using the -d option."
+elif ls /etc/sysconfig/tcedir/sce/"$TARGET".sce.dep > /dev/null 2>&1; then
+	touch /tmp/.importdep
+	echo "Existing dep file found."
+	for I in `cat /etc/sysconfig/tcedir/sce/"$TARGET".sce.dep`; do 
+		checkdep "$I"
+	done
+	if [ -s /tmp/.pkgdeperror ]; then
+		echo " "
+		cat /tmp/.pkgdeperror
+		echo " "
+		if [ ! -f /tmp/.importinteractive ]; then
+			echo "The above files in "$TARGET".sce.dep do not exist in dCore repos."
+			echo -n "Do you want to proceed anyway? (y/N):"
+			read ans
+			if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+				:
+			else
+				exit 1
+			fi
+		else
+			echo "The above files in "$TARGET".sce.dep do not exist in dCore repos."
+		fi
+	fi
+	
+fi
+
+
+
+
 # Check for MS Windows filesystem of TCEDIR, and only continue of RAM 
 # is being used for unpacking.
 MS_MNTS=`mount|awk '$5~/fat|vfat|msdos|ntfs/{printf "%s ",$1}'`
@@ -358,18 +389,14 @@ if [ "$PACKAGELIST" ] && [ ! -f "$TCEDIR"/sce/"$1".sce.lst ]; then
   			echo -n "Creating "$TARGET".sce from package list "$TARGETFILE""
   			mksce "$TARGET" 
   		else
-			if [ -f /tmp/.scelisterror ]; then
+			echo -n "Do you want to create "$TARGET".sce from package list "$TARGETFILE"?  Press (n/N) to import a standard "$TARGET" package if it exists, any key will use the existing package list.  WARNING: Pressing (n/N) will delete "$TARGETFILE" now."
+	  		read ans                   
+	  		if [ "$ans" == "n" ] || [ "$ans" == "N" ]; then  
+	  			sudo rm /tmp/.targetfile
 				mksce "$TARGET" 
+				sudo rm "$TARGETFILE"
 			else
-				echo -n "Do you want to create "$TARGET".sce from package list "$TARGETFILE"?  Press (n/N) to import a standard "$TARGET" package if it exists, any key will use the existing package list.  WARNING: Pressing (n/N) will delete "$TARGETFILE" now."
-	  			read ans                   
-	  			if [ "$ans" == "n" ] || [ "$ans" == "N" ]; then  
-	  				sudo rm /tmp/.targetfile
-					mksce "$TARGET" 
-					sudo rm "$TARGETFILE"
-				else
-					mksce "$TARGET" 
-				fi
+				mksce "$TARGET" 
 			fi
 		fi
 	else 
@@ -383,18 +410,14 @@ elif [ -f "$TCEDIR"/sce/"$1".sce.lst ]; then
   		echo -n "Creating "$TARGET".sce from package list "$TARGETFILE""
   		mksce "$TARGET" 
   	else
-		if [ -f /tmp/.scelisterror ]; then
+		echo -n "Do you want to create "$TARGET".sce from package list "$TARGETFILE"?  Press (n/N) to import a standard "$TARGET" package if it exists, any key will use the existing package list.  WARNING: Pressing (n/N) will delete "$TARGETFILE" now."
+	  	read ans                   
+	  	if [ "$ans" == "n" ] || [ "$ans" == "N" ]; then  
+	  		sudo rm /tmp/.targetfile
 			mksce "$TARGET" 
+			sudo rm "$TARGETFILE"
 		else
-			echo -n "Do you want to create "$TARGET".sce from package list "$TARGETFILE"?  Press (n/N) to import a standard "$TARGET" package if it exists, any key will use the existing package list.  WARNING: Pressing (n/N) will delete "$TARGETFILE" now."
-	  		read ans                   
-	  		if [ "$ans" == "n" ] || [ "$ans" == "N" ]; then  
-	  			sudo rm /tmp/.targetfile
-				mksce "$TARGET" 
-				sudo rm "$TARGETFILE"
-			else
-				mksce "$TARGET" 
-			fi
+			mksce "$TARGET" 
 		fi
 	fi  
 # Below checks for package in the extra repos first, then the 
diff --git a/usr/bin/sce-update b/usr/bin/sce-update
--- a/usr/bin/sce-update
+++ b/usr/bin/sce-update
@@ -66,6 +66,30 @@ fi
 [ -f /tmp/.importupdates ] && sudo rm /tmp/.importupdates
 [ -f /tmp/updateavailable ] && sudo rm /tmp/updateavailable
 [ -f /tmp/importupdated ] && sudo rm /tmp/importupdated
+[ -f /tmp/.importpkgtype ] && sudo rm /tmp/.importpkgtype
+
+cleanup() {
+[ -f /tmp/.sceupdatechoose ] && sudo rm /tmp/.sceupdatechoose
+[ -f /tmp/.scelistchoose ] && sudo rm /tmp/.scelistchoose
+[ -f /tmp/.sceupdateall ] && sudo rm /tmp/.sceupdateall
+[ -f /tmp/.sceupdatelist ] && sudo rm /tmp/.sceupdatelist
+[ -f /tmp/select.ans ] && sudo rm /tmp/select.ans
+[ -f /tmp/.importupdates ] && sudo rm /tmp/.importupdates
+[ -f /tmp/PKGADDDEP ] && sudo rm /tmp/PKGADDDEP
+[ -f /tmp/PKGDATAFILEMD5SUMLIST ] && sudo rm /tmp/PKGDATAFILEMD5SUMLIST
+[ -f /tmp/PKGEXTRAFILES ] && sudo rm /tmp/PKGEXTRAFILES
+[ -f /tmp/PKGEXTRAREPODEP ] && sudo rm /tmp/PKGEXTRAREPODEP
+[ -f /tmp/PKGPREBUILTDEP ] && sudo rm /tmp/PKGPREBUILTDEP
+[ -f /tmp/PREBUILTMD5SUMLIST ] && sudo rm /tmp/PREBUILTMD5SUMLIST
+[ -f /tmp/importupdates ] && sudo rm /tmp/importupdates
+[ -f /tmp/ssupdates ] && sudo rm /tmp/ssupdates
+ls /tmp/*.md5sum > /dev/null 2>&1 && sudo rm /tmp/*.md5sum
+[ -f /tmp/.importpkgtype ] && sudo rm /tmp/.importpkgtype
+[ -f /tmp/.prebuiltmd5sumlist ] && sudo rm /tmp/.prebuiltmd5sumlist
+[ -f /tmp/.pkgextrafilemd5sumlist ] && sudo rm /tmp/.pkgextrafilemd5sumlist
+[ -f /tmp/.pkgprebuilt ] && sudo rm /tmp/.pkgprebuilt
+[ -d /tmp/work ] && sudo rm -r /tmp/work
+}
 
 cd /etc/sysconfig/tcedir/sce
 
@@ -119,74 +143,59 @@ fi
 if [ "$UPDATEALL" == "TRUE" ]; then
 	updateenv
 	echo " "
-	echo "Searching for available updates for chosen SCEs."
+	echo "Searching for available updates for all existing SCEs."
 	## Get list of SCEs to be updated, should be all.
 	for I in `ls *.sce | sed 's:.sce$::' | sort`; do 
-		echo "$I"
+		echo "$I: Checkup for updates.."
 		importupdatecheck "$I" > /dev/null 2>&1
-	done
-	##
-	echo " "
-	if [ "$CHECKONLY" == "TRUE" ]; then
-		if [ -s /tmp/.sceupdatelist ]; then
-			if [ "$NONINTERACTIVE" == "TRUE" ]; then
-				echo "Refer to /tmp/updateavailable for details of package updates."
-				exit 0
+		if grep "^$I$" /tmp/.sceupdatelist > /dev/null 2>&1; then
+			if [ "$CHECKONLY" != "TRUE" ]; then
+				if [ "$NONINTERACTIVE" == "TRUE" ]; then
+					grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"npy "$I"
+					if [ "$?" == "0" ]; then
+						echo "Error in updating "$I".  Exiting.."
+						exit 1
+					fi 
+					echo "$I" >> /tmp/importupdated
+				else
+					echo -n ""$I" is about to be updated.  Press Enter to proceed, y to view package updates, or Ctrl-C to abort.."
+					read ans
+					if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+						less /tmp/updateavailable
+					fi
+					grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"npy "$I"
+					if [ "$?" == "0" ]; then
+						echo "Error in updating "$I".  Exiting.."
+						exit 1
+					fi 
+					echo "$I" >> /tmp/importupdated
+				fi
 			else
-				echo "Do you want to review the list of packages that have updates available?"
-				echo -n "Enter y to view and q to exit reading the package list. (y/N): "
-				read ans
-				if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-					less /tmp/updateavailable
-				fi			
-				exit 0
+				if [ -s /tmp/.sceupdatelist ]; then
+					echo ""$I": ##### Updates are available."
+				fi
 			fi
 		else
-			clear
-			echo "No updates available for chosen SCEs."
-			exit 0
+			echo ""$I": No updates available."
 		fi
-	fi
-	#cat /tmp/.sceupdatelist | tr -d :
-	echo " "
-	if [ -s /tmp/.sceupdatelist ]; then
-		if [ "$NONINTERACTIVE" == "TRUE" ]; then
-			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
-				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
-				if [ "$?" == "0" ]; then
-					echo "Error in updating "$I".  Exiting.."
-					exit 1
-				fi 
-				echo "$I" >> /tmp/importupdated
-			done
-			echo "Refer to /tmp/updateavailable for details of package updates."
-		else
+	done
+		if [ ! -s /tmp/.sceupdatelist ]; then
 			clear
-			cat /tmp/.sceupdatelist | tr -d :
-			echo " "
-			echo " "
-			echo -n "The above SCEs are about to be updated.  Press Enter to proceed, y to view package updates, or Ctrl-C to abort.."
+			echo "No updates available for chosen SCEs at this time."
+			exit 1
+		else
+			echo "Do you want to review the list of packages that had updates available?"
+			echo -n "Enter y to view and q to exit reading the package list. (y/N): "
 			read ans
 			if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
 				less /tmp/updateavailable
-			fi
-			## Update all SCEs
-			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
-				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
-				if [ "$?" == "0" ]; then
-					echo "Error in updating "$I".  Exiting.."
-					exit 1
-				fi 
-				echo "$I" >> /tmp/importupdated
-			done
+			fi			
+			exit 0
 		fi
-		##
-
-	else 
-		clear
-		echo "No updates available for chosen SCEs at this time."
-		exit 1
-	fi
+	##
+	echo " "
+	
+	echo " "
 elif [ -f update/"$UPDATETARGET".sce ]; then
 	cd update/
 	updateenv
@@ -196,62 +205,48 @@ elif [ -f update/"$UPDATETARGET".sce ]; then
 	getDeps "$UPDATETARGET"
 	for I in `echo "$DEPLIST"`; do
 		importupdatecheck "$I" > /dev/null 2>&1
+		if grep "^$I$" /tmp/.sceupdatelist > /dev/null 2>&1; then
+			if [ "$CHECKONLY" != "TRUE" ]; then
+				if [ "$NONINTERACTIVE" == "TRUE" ]; then
+					grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"npy "$I"
+					if [ "$?" == "0" ]; then
+						echo "Error in updating "$I".  Exiting.."
+						exit 1
+					fi 
+					echo "$I" >> /tmp/importupdated
+				else
+					echo -n ""$I" is about to be updated.  Press Enter to proceed, y to view package updates, or Ctrl-C to abort.."
+					if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+						less /tmp/updateavailable
+					fi
+					grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"npy "$I"
+					if [ "$?" == "0" ]; then
+						echo "Error in updating "$I".  Exiting.."
+						exit 1
+					fi 
+					echo "$I" >> /tmp/importupdated
+				fi
+			else
+				if [ -s /tmp/.sceupdatelist ]; then
+					if [ "$NONINTERACTIVE" == "TRUE" ]; then
+						echo ""$I": ##### Updates are available."
+						echo "Refer to /tmp/updateavailable for details of package updates."
+						exit 0
+					else
+						echo "Do you want to review the list of packages that have updates available?"
+						echo -n "Enter y to view and q to exit reading the package list. (y/N): "
+						read ans
+						if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+							less /tmp/updateavailable
+						fi			
+						exit 0
+					fi
+				fi
+			fi
+		fi
 	done
 	unset DEPLIST
-	if [ "$CHECKONLY" == "TRUE" ]; then
-		if [ -s /tmp/.sceupdatelist ]; then
-			if [ "$NONINTERACTIVE" == "TRUE" ]; then
-				echo "Refer to /tmp/updateavailable for details of package updates."
-				exit 0
-			else
-				echo "Do you want to review the list of packages that have updates available?"
-				echo -n "Enter y to view and q to exit reading the package list. (y/N): "
-				read ans
-				if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-					less /tmp/updateavailable
-				fi			
-				exit 0
-			fi
-		else
-			clear
-			echo "No updates available for chosen SCEs."
-			exit 0
-		fi
-	fi
-	if [ -s /tmp/.sceupdatelist ]; then
-		if [ "$NONINTERACTIVE" == "TRUE" ]; then
-			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
-				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
-				if [ "$?" == "0" ]; then
-					echo "Error in updating "$I".  Exiting.."
-					exit 1
-				fi 
-				echo "$I" >> /tmp/importupdated
-			done
-			echo "Refer to /tmp/updateavailable for details of package updates."
-		else
-			clear
-			cat /tmp/.sceupdatelist | tr -d :
-			echo " "
-			echo " "
-			echo -n "The above SCEs are about to be updated.  Press Enter to proceed, y to view package updates, or Ctrl-C to abort.."
-			read ans
-			if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-				less /tmp/updateavailable
-			fi
-			## Update all SCEs
-			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
-				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
-				if [ "$?" == "0" ]; then
-					echo "Error in updating "$I".  Exiting.."
-					exit 1
-				fi 
-				echo "$I" >> /tmp/importupdated
-			done
-		fi
-		##
-
-	else 
+	if [ ! -s /tmp/.sceupdatelist ]; then
 		clear
 		echo "No updates available for chosen SCEs at this time."
 		exit 1
@@ -265,66 +260,55 @@ elif [ -f "$UPDATETARGET".sce ]; then
 	getDeps "$UPDATETARGET"
 	for I in `echo "$DEPLIST"`; do
 		importupdatecheck "$I" > /dev/null 2>&1
+		if grep "^$I$" /tmp/.sceupdatelist > /dev/null 2>&1; then
+			if [ "$CHECKONLY" != "TRUE" ]; then
+				if [ "$NONINTERACTIVE" == "TRUE" ]; then
+					grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"npy "$I"
+					if [ "$?" == "0" ]; then
+						echo "Error in updating "$I".  Exiting.."
+						exit 1
+					fi 
+					echo "$I" >> /tmp/importupdated
+				else
+					echo -n ""$I" is about to be updated.  Press Enter to proceed, y to view package updates, or Ctrl-C to abort.."
+					read ans
+					if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+						less /tmp/updateavailable
+					fi
+					grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"npy "$I"
+					if [ "$?" == "0" ]; then
+						echo "Error in updating "$I".  Exiting.."
+						exit 1
+					fi 
+					echo "$I" >> /tmp/importupdated
+				fi
+			else
+				if [ "$NONINTERACTIVE" == "TRUE" ]; then
+					echo ""$I": ##### Updates are available."
+					echo "Refer to /tmp/updateavailable for details of package updates."
+					exit 0
+				else
+					echo "Do you want to review the list of packages that have updates available?"
+					echo -n "Enter y to view and q to exit reading the package list. (y/N): "
+					read ans
+					if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+						less /tmp/updateavailable
+					fi			
+					exit 0
+				fi
+			fi
+		else
+			echo ""$I": No updates available."
+		fi
 	done
 	unset DEPLIST
-	if [ "$CHECKONLY" == "TRUE" ]; then
-		if [ -s /tmp/.sceupdatelist ]; then
-			if [ "$NONINTERACTIVE" == "TRUE" ]; then
-				echo "Refer to /tmp/updateavailable for details of package updates."
-				exit 0
-			else
-				echo "Do you want to review the list of packages that have updates available?"
-				echo -n "Enter y to view and q to exit reading the package list. (y/N): "
-				read ans
-				if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-					less /tmp/updateavailable
-				fi			
-				exit 0
-			fi
-		else
-			clear
-			echo "No updates available for chosen SCEs."
-			exit 0
-		fi
-	fi
-	if [ -s /tmp/.sceupdatelist ]; then
-		if [ "$NONINTERACTIVE" == "TRUE" ]; then
-			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
-				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
-				if [ "$?" == "0" ]; then
-					echo "Error in updating "$I".  Exiting.."
-					exit 1
-				fi 
-				echo "$I" >> /tmp/importupdated
-			done
-			echo "Refer to /tmp/updateavailable for details of package updates."
-		else
-			clear
-			cat /tmp/.sceupdatelist | tr -d :
-			echo " "
-			echo " "
-			echo -n "The above SCEs are about to be updated.  Press Enter to proceed, y to view package updates, or Ctrl-C to abort.."
-			read ans
-			if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-				less /tmp/updateavailable
-			fi
-			## Update all SCEs
-			for I in `cat /tmp/.sceupdatelist | tr -d :`; do
-				grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$I"
-				if [ "$?" == "0" ]; then
-					echo "Error in updating "$I".  Exiting.."
-					exit 1
-				fi 
-				echo "$I" >> /tmp/importupdated
-			done
-		fi
-		##
-
-	else 
+	if [ ! -s /tmp/.sceupdatelist ]; then
 		clear
 		echo "No updates available for chosen SCEs at this time."
 		exit 1
 	fi
+	
+	
 elif [ "$SELECT" == "TRUE" ]; then
 	ls *.sce | sed 's:.sce$::' | sort > /tmp/.scelistchoose
 	while true; do 
@@ -350,83 +334,57 @@ You can choose more than one, and enter "q" for quit when you have completed you
 	if [ "$ANS" == "y" ] || [ "$ANS" == "Y" ]; then
 		updateenv
 		## Update selected SCEs
-		for I in `cat /tmp/.sceupdatechoose | tr -d :`; do
+		for D in `cat /tmp/.sceupdatechoose | tr -d :`; do
 			echo " "
-			echo "Checking for updates for "$I".sce.."
+			echo "Checking for updates for "$D".sce.."
 			unset DEPLIST
-			getDeps "$I"
-			for D in `echo "$DEPLIST"`; do
-				importupdatecheck "$D" > /dev/null 2>&1
-			done
-			#unset DEPLIST
-		done
-		if [ "$CHECKONLY" == "TRUE" ]; then
-			if [ -s /tmp/.sceupdatelist ]; then
-				if [ "$NONINTERACTIVE" == "TRUE" ]; then
-					echo "Refer to /tmp/updateavailable for details of package updates."
-					exit 0
+			getDeps "$D"
+			for I in `echo "$DEPLIST"`; do
+				importupdatecheck "$I" > /dev/null 2>&1
+				if grep "^$I$" /tmp/.sceupdatelist > /dev/null 2>&1; then
+					if [ "$CHECKONLY" != "TRUE" ]; then
+						if [ "$NONINTERACTIVE" == "TRUE" ]; then
+							grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"npy "$I"
+							if [ "$?" == "0" ]; then
+								echo "Error in updating "$I".  Exiting.."
+								exit 1
+							fi 
+							echo "$I" >> /tmp/importupdated
+						else
+							echo -n ""$I" is about to be updated.  Press Enter to proceed, y to view package updates, or Ctrl-C to abort.."
+							read ans
+							if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+								less /tmp/updateavailable
+							fi
+							grep "^$I$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"npy "$I"
+							if [ "$?" == "0" ]; then
+								echo "Error in updating "$I".  Exiting.."
+								exit 1
+							fi 
+							echo "$I" >> /tmp/importupdated
+						fi
+					else
+							echo ""$I": ##### Updates are available."
+					fi
 				else
-					echo "Do you want to review the list of packages that have updates available?"
-					echo -n "Enter y to view and q to exit reading the package list. (y/N): "
-					read ans
-					if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-						less /tmp/updateavailable
-					fi			
-					exit 0
+					echo ""$I": No updates available."	
 				fi
-			else
-				clear
-				echo "No updates available for chosen SCEs."
-				exit 0
-			fi
-		fi
-	
-		## Update SCEs
-		if [ -s /tmp/.sceupdatelist ]; then
-			if [ "$NONINTERACTIVE" == "TRUE" ]; then
-				for I in `cat /tmp/.sceupdatelist | tr -d :`; do
-					getDeps "$I"
-				done
-				for D in `echo "$DEPLIST"`; do
-					grep "^$D$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$D"
-					if [ "$?" == "0" ]; then
-						echo "Error in updating "$I".  Exiting.."
-						exit 1
-					fi 
-					echo "$D" >> /tmp/importupdated
-				done
-				echo "Refer to /tmp/updateavailable for package update details."
-			else
-				clear
-				cat /tmp/.sceupdatelist | tr -d :
-				echo " "
-				echo " "
-				echo -n "The above SCEs are about to be updated.  Press Enter to proceed, y to view package updates, or Ctrl-C to abort.."
-				read ans
-				if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-					less /tmp/updateavailable
-				fi
-				## Update all SCEs
-				#for I in `cat /tmp/.sceupdatelist | tr -d :`; do
-				#	getDeps "$I"
-				#done
-				for D in `echo "$DEPLIST"`; do
-					grep "^$D$" /tmp/importupdated > /dev/null 2>&1 || sce-import -"$OPTIONS"np "$D"
-					if [ "$?" == "0" ]; then
-						echo "Error in updating "$I".  Exiting.."
-						exit 1
-					fi 
-					echo "$D" >> /tmp/importupdated
-				done
-			fi
-			##
-	
-		else 
+			done
+			unset DEPLIST
+		done
+		if [ ! -s /tmp/.sceupdatelist ]; then
 			clear
 			echo "No updates available for chosen SCEs at this time."
 			exit 1
+		else
+			echo "Do you want to review the list of packages that had updates available?"
+			echo -n "Enter y to view and q to exit reading the package list. (y/N): "
+			read ans
+			if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
+				less /tmp/updateavailable
+			fi			
+			exit 0
 		fi
-		##
 	else
 		echo "Exit was chosen, no action will be taken."
 	fi
@@ -434,27 +392,7 @@ else
 	echo ""$UPDATETARGET" is not an existing SCE file.  Exiting.."
 fi
 
-[ -f /tmp/.sceupdatechoose ] && sudo rm /tmp/.sceupdatechoose
-[ -f /tmp/.scelistchoose ] && sudo rm /tmp/.scelistchoose
-[ -f /tmp/.sceupdateall ] && sudo rm /tmp/.sceupdateall
-[ -f /tmp/.sceupdatelist ] && sudo rm /tmp/.sceupdatelist
-[ -f /tmp/select.ans ] && sudo rm /tmp/select.ans
-[ -f /tmp/.importupdates ] && sudo rm /tmp/.importupdates
-[ -f /tmp/PKGADDDEP ] && sudo rm /tmp/PKGADDDEP
-[ -f /tmp/PKGDATAFILEMD5SUMLIST ] && sudo rm /tmp/PKGDATAFILEMD5SUMLIST
-[ -f /tmp/PKGEXTRAFILES ] && sudo rm /tmp/PKGEXTRAFILES
-[ -f /tmp/PKGEXTRAREPODEP ] && sudo rm /tmp/PKGEXTRAREPODEP
-[ -f /tmp/PKGPREBUILTDEP ] && sudo rm /tmp/PKGPREBUILTDEP
-[ -f /tmp/PREBUILTMD5SUMLIST ] && sudo rm /tmp/PREBUILTMD5SUMLIST
-[ -f /tmp/importupdates ] && sudo rm /tmp/importupdates
-[ -f /tmp/ssupdates ] && sudo rm /tmp/ssupdates
-ls /tmp/*.md5sum > /dev/null 2>&1 && sudo rm /tmp/*.md5sum
-[ -f /tmp/.importpkgtype ] && sudo rm /tmp/.importpkgtype
-[ -f /tmp/.importpkgtype ] && sudo rm /tmp/.importpkgtype
-[ -f /tmp/.prebuiltmd5sumlist ] && sudo rm /tmp/.prebuiltmd5sumlist
-[ -f /tmp/.pkgextrafilemd5sumlist ] && sudo rm /tmp/.pkgextrafilemd5sumlist
-[ -f /tmp/.pkgprebuilt ] && sudo rm /tmp/.pkgprebuilt
-[ -d /tmp/work ] && sudo rm -r /tmp/work
+
 
 if ls /tmp/*.pkglist > /dev/null 2>&1; then 
 	sudo rm /tmp/*.pkglist
