Changes provided by nitram.

diff --git a/usr/bin/sce-import b/usr/bin/sce-import
--- a/usr/bin/sce-import
+++ b/usr/bin/sce-import
@@ -16,9 +16,9 @@ BUILD=`getBuild`
 HERE=`pwd`
 
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
-	echo "${YELLOW}sce-import - Search, convert, install DEB and pre-built packages as local SCEs,"
-        echo "             use simple name (nano not nano_*_i386.deb), may use option combos,"
-        echo "             also see /etc/sysconfig/sceconfig, locale.nopurge and sce.purge.${NORMAL}"
+	echo "${YELLOW}sce-import - Search, convert, install DEB and pre-built packages as local SCEs.${NORMAL}"
+        echo "             Use simple name (nano not nano_*_i386.deb). May use option combos."
+        echo "             Also see /etc/sysconfig/sceconfig, locale.nopurge and sce.purge."
 	echo "${YELLOW}"sce-import"${NORMAL}             Prompt, enter starting characters of package sought."
 	echo "${YELLOW}"sce-import PKG"${NORMAL}         Search packages that start with desired package name."
 	echo "${YELLOW}"sce-import -b PKG"${NORMAL}      Add resulting SCE to sceboot.lst."
@@ -45,21 +45,24 @@ fi
 mksce() {
 	if [ "$FLAGS" ]
 	then
-		sudo deb2sce "$FLAGS" "$1" 
+		sudo deb2sce "$FLAGS" "$1"
 		if [ "$?" != "0" ]; then
 			exit 1
-		fi      
+		fi
+		cleanup
 	else
-		sudo deb2sce "$1"  
+		sudo deb2sce "$1"
 		if [ "$?" != "0" ]; then
 			exit 1
-		fi           
+		fi
+		cleanup
 	fi
 
 }
 
 exit_tcnet() {
-	echo "Issue connecting to `cat /opt/tcemirror`, exiting.."
+	echo " "
+	echo "${YELLOW}Warning:${NORMAL} Issue connecting to `cat /opt/tcemirror`, exiting.."
 	exit 1
 }
 
@@ -97,7 +100,7 @@ if [ ! "$NOLOCK" == "TRUE" ]; then
 	if [ -f /tmp/.scelock ]; then
 		LOCK=`cat /tmp/.scelock`
 		if /bb/ps -o pid | sed -e 's/^[ \t]*//'| grep "^$LOCK$" | /bb/grep -v grep > /dev/null 2>&1; then
-			echo "Another SCE utility is presently in use, exiting.."
+			echo "${YELLOW}Warning:${NORMAL} Another SCE utility is presently in use, exiting.."
 			exit 1
 		fi
 	fi
@@ -107,15 +110,14 @@ fi
 
 NICE=`grep "^NICE=" /etc/sysconfig/sceconfig | cut -f2 -d=`
 if [ -n "$NICE" ]; then
-	echo " "
 	if [ "$NICE" -gt 19 ]; then
 		NICE=19
-		echo "Using nice level 19, 19 is the highest possible nice value."
+		echo "* Using nice level 19, 19 is the highest possible nice value."
 	elif [ 0 -gt "$NICE" ]; then
 		NICE=0
-		echo "Using nice level "$NICE", only root can use negative nice values."
+		echo "* Using nice level "$NICE", only root can use negative nice values."
 	else 
-		echo "Using nice level "$NICE"."
+		echo "* Using nice level "$NICE"."
 	fi
 	/bb/renice -n "$NICE" -p $$
 fi
@@ -135,6 +137,7 @@ shift `expr $OPTIND - 1`
 [ "$FLAGS" ] && FLAGS="-$FLAGS"
 TARGET="$1"
 
+cleanup () {
 [ -d /tmp/work ] && sudo rm -f /tmp/work/* > /dev/null 2>&1
 [ -f /tmp/.viewpkgs ] && sudo rm /tmp/.viewpkgs
 [ -f /tmp/.importinteractive ] && sudo rm /tmp/.importinteractive
@@ -165,7 +168,13 @@ TARGET="$1"
 [ -f /tmp/.recommends ] && sudo rm /tmp/.recommends
 [ -f /tmp/.suggests ] && sudo rm /tmp/.suggests
 [ -f /tmp/.scenoconfig ] && sudo rm /tmp/.scenoconfig
+## Added:
+[ -f /tmp/.pkglist ] && sudo rm /tmp/.pkglist
+[ -f /tmp/import.log ] && sudo rm /tmp/import.log
+[ -f /tmp/.sceimportselect ] && sudo rm /tmp/.sceimportselect
+}
 
+cleanup
 
 # Strip .sce suffix of package and preceding directory 
 # and preceding directory if specified on command line.
@@ -173,113 +182,108 @@ TARGET=`basename "$TARGET"`
 TARGET=${TARGET%%.sce}
 TARGET=${TARGET%%.sce.lst}
 
-echo " "
-
 # Determine if debinx is desired to be updated in this session.
 if [ "$PRESERVEDEBINXMODE" = "TRUE" ] ; then
-	echo "Using the -p option."
+	echo "* Using the -p option."
 elif grep -i "^PRESERVEDEBINXMODE=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
 	PRESERVEDEBINXMODE=TRUE
-	echo "Using the -p option."
+	echo "* Using the -p option."
 else
-	echo "Using the -u option."
+	echo "* Using the -u option."
 fi
 
 # Noconfig mode, overlooking sceconfig, sce.purge, and locale.nopurge
 if [ "$NOCONFIG" == "TRUE" ]; then
 	touch /tmp/.scenoconfig
-	echo "Using the -z option."
+	echo "* Using the -z option."
 fi
 
 # Determine if non-interactive mode is being used.
 if grep -i "^NONINTERACTIVE=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
 	touch /tmp/.importinteractive
-	echo "Using the -n option."
+	echo "* Using the -n option."
 elif [ "$NONINTERACTIVE" == "TRUE" ]; then
 	touch /tmp/.importinteractive
-	echo "Using the -n option."
+	echo "* Using the -n option."
 fi
 
 if grep -wq "^$TARGET$" "$DEBINXDIR"/PKGEXCLUDELIST > /dev/null 2>&1; then
 	echo " "
-	echo "$TARGET is a blocked package, exiting.."
+	echo "${YELLOW}Warning:${NORMAL} $TARGET is a blocked package, exiting.."
 	exit 0
 fi
 
 # Determine if the size option is being used.
 if grep -i "^SIZE=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
 	touch /tmp/.importsize
-	echo "Using the -s option."
+	echo "* Using the -s option."
 elif [ "$SIZE" == "TRUE" ]; then
 	touch /tmp/.importsize
-	echo "Using the -s option."
+	echo "* Using the -s option."
 fi
 
 # Determine if the viewpackges option is being used.
 if grep -i "^VIEWPKGS=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
 	touch /tmp/.viewpkgs
-	echo "Using the -v option."
+	echo "* Using the -v option."
 elif [ "$VIEWPKGS" == "TRUE" ]; then
 	touch /tmp/.viewpkgs
-	echo "Using the -v option."
+	echo "* Using the -v option."
 fi
 
 # Determine if the checkall option is being used.
 if grep -i "^CHECKALL=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
 	export CHECKALL=TRUE
-	echo "Using the -c option."
+	echo "* Using the -c option."
 elif [ "$CHECKALL" == "TRUE" ]; then
-	echo "Using the -c option."
+	echo "* Using the -c option."
 fi
 
 # Determine if RAM is going to be used for unpacking.
 if grep -i "^RAM=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
 	touch /tmp/.importram
-	echo "Using the -r option."
+	echo "* Using the -r option."
 elif [ "$RAM" == "TRUE" ]; then
 	touch /tmp/.importram
-	echo "Using the -r option."
+	echo "* Using the -r option."
 fi
 
 # Determine if docs are to be kept (/usr/share/doc, /usr/share/man, etc).
 if grep -i "^KEEPDOC=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
 	touch /tmp/.keepdoc
-	echo "Using the -k option."
+	echo "* Using the -k option."
 elif [ "$KEEPDOC" == "TRUE" ]; then
 	touch /tmp/.keepdoc
-	echo "Using the -k option."
+	echo "* Using the -k option."
 fi
 
 # Determine if including 'Recommended' packages are desired.
 if grep -i "^RECOMMENDS=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
 	touch /tmp/.recommends
-	echo "Using the -R option."
+	echo "* Using the -R option."
 elif [ "$RECOMMENDS" == "TRUE" ]; then
 	touch /tmp/.recommends
-	echo "Using the -R option."
+	echo "* Using the -R option."
 fi
 
 # Determine if including 'Suggested' packages are desired.
 if grep -i "^SUGGESTS=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
 	touch /tmp/.suggests
-	echo "Using the -S option."
+	echo "* Using the -S option."
 elif [ "$SUGGESTS" == "TRUE" ]; then
 	touch /tmp/.suggests
-	echo "Using the -S option."
+	echo "* Using the -S option."
 fi
 
 # Determine if the -d option or the existence of a dep file
 # is present and use dep file if found.
 if [ "$DEPS" == "TRUE" ]; then
 	touch /tmp/.importdep
-	echo "Using the -d option."
+	echo "* Using the -d option."
 elif ls /etc/sysconfig/tcedir/sce/"$TARGET".sce.dep > /dev/null 2>&1; then
 	touch /tmp/.importdep
-	echo " "
-	echo "Existing dependency file found."
+	echo "* Existing dependency file found."
 fi
-
-echo " "
 
 # Check for ntfs TCEDIR without ntfs-3g loaded, and exit if so.
 MS_MNTS=`mount|awk '$5~/ntfs/{printf "%s ",$1}'`
@@ -289,9 +293,9 @@ case "$MS_MNTS" in
 			*"$MNTDEV"* )
 				
 				echo " "
-				echo "${YELLOW}Warning:${NORMAL} "$REALDIR" resides on a read only ntfs filesystem, exiting.."
-				exit 1
-					
+				echo "${YELLOW}Warning:${NORMAL} "$REALDIR" resides on a read only NTFS filesystem,"
+				echo "         ntfs-3g needed to write to NTFS, exiting.."
+				exit 1					
 			;;
 
 esac
@@ -307,7 +311,7 @@ case "$MS_MNTS" in
 				if [ ! -f /tmp/.importram ]; then 
 					echo " "
 					echo "${YELLOW}Warning:${NORMAL} "$REALDIR" resides on a Windows filesystem."
-					echo "Please try again with the -r flag to unpack files in RAM, exiting.."
+					echo "Try again with the -r flag to unpack files in RAM, exiting.."
 					exit 1
 				fi	
 			;;
@@ -318,26 +322,29 @@ if [ "$PRESERVEDEBINXMODE" != "TRUE" ]; then
 	sudo debGetEnv "$2"
 	if [ "$?" != "0" ]; then
 		echo " "
-		echo "Error updating DEBINX files, exiting.."
+		echo "${YELLOW}Warning:${NORMAL} Error updating DEBINX files, exiting.."
 		exit 1
 	fi
 else
 	cd "$DEBINXDIR"
 	if [ ! -s /etc/sysconfig/tcedir/import/debinx/debinx ] || [ ! -f deb2sce.tar.gz ]; then
-		echo "${YELLOW}Warning:${NORMAL} Please run sce-import without the -p option to update DEBINX data."
+		echo " "
+		echo "${YELLOW}Warning:${NORMAL} Run sce-import without the -p option to update DEBINX data, exiting.."
 		exit 1
 	
 	else
 		DEBINX=`cat /etc/sysconfig/tcedir/import/debinx/debinx`
 		if [ ! -f "$DEBINX" ]; then
-			echo "${YELLOW}Warning:${NORMAL} Please run sce-import without the -p option to update DEBINX data."
+			echo " "
+			echo "${YELLOW}Warning:${NORMAL} Run sce-import without the -p option to update DEBINX data, exiting.."
 			exit 1
 		fi
 	fi
 	if [ -s /etc/sysconfig/tcedir/import/debinx/debinx_security ]; then
 		DEBINX_SECURITY=`cat /etc/sysconfig/tcedir/import/debinx/debinx_security`
 		if [ ! -f "$DEBINX_SECURITY" ]; then
-			echo "${YELLOW}Warning:${NORMAL} Please run sce-import without the -p option to update DEBINX data."
+			echo " "
+			echo "${YELLOW}Warning:${NORMAL} Run sce-import without the -p option to update DEBINX data, exiting.."
 			exit 1
 		fi
 	fi
@@ -384,24 +391,26 @@ if [ "$PACKAGELIST" == "TRUE" ] || [ -f "$TCEDIR"/sce/"$TARGET".sce.lst ]; then
 			cat /tmp/.pkglisterror
 			echo " "
 			if [ ! -f /tmp/.importinteractive ]; then
-				echo "${YELLOW}Warning:${NORMAL} The above files in "$TARGETFILE" do not exist in dCore repos."
+				echo "${YELLOW}Warning:${NORMAL} The above package(s) in "$TARGETFILE" do not exist."
 				echo " "
-				echo -n "Press Enter to proceed anyway, (q)uit to exit: "
+				echo -n "Press Enter to import the remaining list anyway, (q)uit to exit: "
 				read ans
 				if [ "$ans" == "y" ] || [ "$ans" == "Y" ] || [ "$ans" == "" ]; then
 					:
 				else
+					cleanup
 					exit 1
 				fi
 			else
-				echo "The above files in "$TARGETFILE" do not exist in dCore repos."
+				echo "${YELLOW}Warning:${NORMAL} The above package(s) in "$TARGETFILE" do not exist,"
+				echo "         proceeding to import remaining list."
+				echo " "
 			fi
 		fi
 		sudo cp $TARGETFILE /tmp/.targetfile
 		#TARGET=`basename $1 .sce.lst`
 	elif [ -s "$TCEDIR"/sce/"$TARGET".sce.lst ]; then
-		echo " "
-		echo "Existing list file found."
+		echo "* Existing list file found."
 		TARGETFILE=""$TCEDIR"/sce/"$TARGET".sce.lst"
 		for I in `cat "$TARGETFILE"`; do
 			checklist "$I"
@@ -411,28 +420,31 @@ if [ "$PACKAGELIST" == "TRUE" ] || [ -f "$TCEDIR"/sce/"$TARGET".sce.lst ]; then
 			cat /tmp/.pkglisterror
 			echo " "
 			if [ ! -f /tmp/.importinteractive ]; then
-				echo "${YELLOW}Warning:${NORMAL} The above files in "$TARGETFILE" do not exist in dCore repos."
+				echo "${YELLOW}Warning:${NORMAL} The above package(s) in "$TARGETFILE" do not exist."
 				echo " "
-				echo -n "Press Enter to proceed anyway, (q)uit exits: "
+				echo -n "Press Enter to import the remaining list anyway, (q)uit to exit: "
 				read ans
 				if [ "$ans" == "y" ] || [ "$ans" == "Y" ] || [ "$ans" == "" ]; then
 					:
 				else
+					cleanup
 					exit 1
 				fi
 			else
-				echo "The above files in "$TARGETFILE" do not exist in dCore repos."
+				echo "${YELLOW}Warning:${NORMAL} The above package(s) in "$TARGETFILE" do not exist,"
+				echo "         proceeding to import remaining list."
+				echo " "
 			fi
 		fi
 		sudo cp "$TCEDIR"/sce/"$TARGET".sce.lst /tmp/.targetfile
 	elif [ ! "$1" ]; then
 		echo " "
-		echo "Please specify a target file when using the -l option, exiting.."
+		echo "${YELLOW}Warning:${NORMAL} Specify a target file when using the -l option, exiting.."
 		exit 0
 	else
 		echo " "
-		echo "Neither '"$1"' or "$TCEDIR"/sce/"$1".sce.lst files exist,"
-		echo "exiting.."
+		echo "${YELLOW}Warning:${NORMAL} Neither '"$1"' or "$TCEDIR"/sce/"$1".sce.lst"
+		echo "         files exist, exiting.."
 		exit 0
 	fi
 fi
@@ -440,7 +452,7 @@ fi
 # When no package is specified on command line, ask for one.
 if [ -z "$TARGET" ] && [ "$CHECKALL" == "TRUE" ]; then
 	echo " "
-	echo -n "Enter search characters contained in package sought: "
+	echo -n "Enter characters contained in package sought: "
 	read TARGET
 elif [ -z "$TARGET" ]; then
 	echo " "
@@ -461,21 +473,26 @@ if [ "$PACKAGELIST" ] && [ ! -f "$TCEDIR"/sce/"$1".sce.lst ]; then
 	if [ -f "$TARGETFILE" ]; then
   		echo " "
   		if [ -f /tmp/.importinteractive ]; then
-  			echo "Creating "$TARGET".sce from "$TARGETFILE"."
+  			echo "* Creating "$TARGET".sce from "$TARGETFILE"."
   			mksce "$TARGET"
 			exit 0
   		else
+			echo " "
                         echo "${YELLOW}Create "$TARGET".sce from "$TARGETFILE"?${NORMAL}"
 			echo " "
-			echo "Press Enter to use this package list or enter '(n)o' to import a standard"
-			echo "'"$TARGET"' package if it exists, Ctrl-C aborts."
+			echo "Press Enter to use this package list, (n)o to import a standard"
+			echo "'"$TARGET"' package if it exists, (q)uit exits."
                         echo " "
                         echo -n "${YELLOW}Warning:${NORMAL} Entering '(n)o' will delete "$TARGETFILE": "
-                        read ans                  
+                        read ans
+			echo " "
 	  		if [ "$ans" == "n" ] || [ "$ans" == "N" ]; then  
 	  			sudo rm /tmp/.targetfile
 				mksce "$TARGET" 
 				sudo rm "$TARGETFILE"
+				exit 0
+	  		elif [ "$ans" == "q" ] || [ "$ans" == "Q" ]; then
+				cleanup
 				exit 0
 			else
 				mksce "$TARGET"
@@ -483,28 +500,33 @@ if [ "$PACKAGELIST" ] && [ ! -f "$TCEDIR"/sce/"$1".sce.lst ]; then
 			fi
 		fi
 	else
-		echo "Please specify a target file when using the -l option, exiting.."
+		echo " "
+		echo "${YELLOW}Warning:${NORMAL} Specify a target file when using the -l option, exiting.."
 		exit 1
 	fi  
 # Below is where an existing .lst file is found in sce dir.
 elif [ -f "$TCEDIR"/sce/"$TARGET".sce.lst ]; then
-	echo " "
   	if [ -f /tmp/.importinteractive ]; then
-  		echo -n "Creating "$TARGET".sce from "$TARGETFILE"."
+  		echo "* Creating "$TARGET".sce from "$TARGETFILE"."
   		mksce "$TARGET"
 		exit 0
   	else
-	  	echo "${YELLOW}Create "$TARGET".sce from "$TARGETFILE"?${NORMAL}"
 		echo " "
-		echo "Press Enter to use this package list or enter (n)o to import a standard"
-		echo "'"$TARGET"' package if it exists, Ctrl-C aborts."
+                echo "${YELLOW}Create "$TARGET".sce from "$TARGETFILE"?${NORMAL}"
+		echo " "
+		echo "Press Enter to use this package list, (n)o to import a standard"
+		echo "'"$TARGET"' package if it exists, (q)uit exits."
                 echo " "
 		echo -n "${YELLOW}Warning:${NORMAL} Entering (n)o will delete "$TARGETFILE": "
                 read ans
+		echo " "
 	  	if [ "$ans" == "n" ] || [ "$ans" == "N" ]; then  
 	  		sudo rm /tmp/.targetfile
 			mksce "$TARGET" 
 			sudo rm "$TARGETFILE"
+			exit 0
+  		elif [ "$ans" == "q" ] || [ "$ans" == "Q" ]; then
+			cleanup
 			exit 0
 		else
 			mksce "$TARGET"
@@ -526,7 +548,8 @@ elif [ "$CHECKALL" == "TRUE" ]; then
 				DEB=`sudo grep -i "^$TARGET:" "$DEBINXDIR"/PKGPREBUILTDEP | cut -f1 -d:`
 			fi
 			if [ -z "$DEB" ]; then
-				echo "'"$TARGET"' is not available as a package, exiting.."
+				echo " "
+				echo "${YELLOW}Warning:${NORMAL} '"$TARGET"' is not available as a package, exiting.."
 				exit 1
 			fi     
 		else
@@ -540,6 +563,7 @@ elif [ "$CHECKALL" == "TRUE" ]; then
 				if [ "$ans" == "y" ] || [ "$ans" == "Y" ] || [ "$ans" == "" ]; then
 					:
 				else
+					cleanup
 					exit 0
 				fi
 			else
@@ -548,8 +572,7 @@ elif [ "$CHECKALL" == "TRUE" ]; then
   				[ "$DEB" == "q" ] || [ "$DEB" == "" ] && exit 1  
 			fi   
 		fi 
-		echo " "
-  		echo "Importing ${YELLOW}$DEB${NORMAL}."
+  		echo "* Importing ${YELLOW}$DEB${NORMAL}."
   		mksce "$DEB"
   		exit 0
 	fi 
@@ -566,7 +589,8 @@ elif [ "$CHECKALL" != "TRUE" ]; then
 				DEB=`sudo grep -i "^$TARGET:" "$DEBINXDIR"/PKGPREBUILTDEP | cut -f1 -d:`
 			fi
 			if [ -z "$DEB" ]; then
-				echo "'"$TARGET"' is not available as a package, exiting.."
+				echo " "
+				echo "${YELLOW}Warning:${NORMAL} '"$TARGET"' is not available as a package, exiting.."
 				exit 1
 			fi  
 		 else
@@ -580,6 +604,7 @@ elif [ "$CHECKALL" != "TRUE" ]; then
 				if [ "$ans" == "y" ] || [ "$ans" == "Y" ] || [ "$ans" == "" ]; then
 					:
 				else
+					cleanup
 					exit 0
 				fi
 			else
@@ -589,8 +614,7 @@ elif [ "$CHECKALL" != "TRUE" ]; then
 			fi
         
 		fi
-		echo " "
-  		echo "Importing ${YELLOW}"$DEB"${NORMAL}."
+  		echo "* Importing ${YELLOW}"$DEB"${NORMAL}."
   		mksce "$DEB"
   		exit 0
 	fi
@@ -598,5 +622,5 @@ elif [ "$CHECKALL" != "TRUE" ]; then
 fi
 
 echo " "
-echo "'"$TARGET"' is not available as a package, exiting.."
+echo "${YELLOW}Warning:${NORMAL} '"$TARGET"' is not available as a package, exiting.."
 exit 0
diff --git a/usr/bin/sce-update b/usr/bin/sce-update
--- a/usr/bin/sce-update
+++ b/usr/bin/sce-update
@@ -13,19 +13,18 @@ unset DEPLIST SCEBOOTLIST VIEWED
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
         echo " "
 	echo "${YELLOW}sce-update - Check and update all or individual SCE(s) including any dependency"
-	echo "             SCE(s), view DEBINX (Debian index) diff and available updates if"
-	echo "             desired, may use some option combinations.${NORMAL}"
-	echo " "
+	echo "             SCE(s).${NORMAL} View DEBINX (Debian index) diff and available updates if"
+	echo "             desired. May use some option combinations."
 	echo "Usage:"
-	echo " "
 	echo "${YELLOW}"sce-update"${NORMAL}         Menu prompt, choose SCE(s) to check, update if required."
        	echo "${YELLOW}"sce-update SCE"${NORMAL}     Check a specific SCE for update, update if required."
-	echo "${YELLOW}"sce-update -a"${NORMAL}      Check all system SCEs for updates, view old/new DEBINX diff"
-	echo "                   and available updates if desired, update SCEs if required."
 	echo "${YELLOW}"sce-update -n SCE"${NORMAL}  Non-interactive mode, check a specific SCE for updates,"
 	echo "                   update if required."
+	echo "${YELLOW}"sce-update -a"${NORMAL}      Check all system SCEs for updates, view DEBINX diff and"
+	echo "                   available updates if desired, update SCEs if required."
 	echo "${YELLOW}"sce-update -na"${NORMAL}     Non-interactive mode, check all SCEs for updates,"
 	echo "                   update if required."
+	echo "${YELLOW}"sce-update -b"${NORMAL}      Check sceboot.lst SCEs for updates, update if required."
 	echo "${YELLOW}"sce-update -c"${NORMAL}      Menu prompt, check selected SCE(s) for updates only,"
         echo "                   no actual updates performed."
 	echo "${YELLOW}"sce-update -r"${NORMAL}      Unpack files in RAM during an SCE update re-import."
@@ -33,9 +32,6 @@ if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
 	echo "                   re-import, warn as needed."
 	echo "${YELLOW}"sce-update -z"${NORMAL}      Ignore /etc/sysconfig/sceconfig preferences, use only"
         echo "                   current command line options."
-	echo "${YELLOW}"sce-update -b"${NORMAL}      Check SCE entries in your sceboot.lst and any"
-	echo "                   applicable SCE dependencies."
-	echo " "
 	exit 0
 fi
 
@@ -44,7 +40,7 @@ if [ ! "$NOLOCK" == "TRUE" ]; then
 	if [ -f /tmp/.scelock ]; then
 		LOCK=`cat /tmp/.scelock`
 		if /bb/ps -o pid | sed -e 's/^[ \t]*//'| grep "^$LOCK$" | /bb/grep -v grep > /dev/null 2>&1; then
-			echo "Another SCE utility is presently in use, exiting.."
+			echo "${YELLOW}Warning:${NORMAL} Another SCE utility is presently in use, exiting.."
 			exit 1
 		fi
 	fi
@@ -55,7 +51,7 @@ fi
 while getopts canrszb OPTION
 do
 	case ${OPTION} in
-		r) RAM=TRUE ;;
+		r) RAM=TRUE;;
 		n) NONINTERACTIVE=TRUE ;;
 		c) CHECKONLY=TRUE ;;
 		a) UPDATEALL=TRUE ;;
@@ -67,21 +63,21 @@ do
 	esac
 done
 
+
 NICE=`grep "^NICE=" /etc/sysconfig/sceconfig | cut -f2 -d=`
 if [ -n "$NICE" ]; then
-	echo " "
 	if [ "$NICE" -gt 19 ]; then
 		NICE=19
-		echo "Using nice level 19, 19 is the highest possible nice value."
+		echo "* Using nice level 19, 19 is the highest possible nice value."
 	elif [ 0 -gt "$NICE" ]; then
 		NICE=0
-		echo "Using nice level "$NICE", only root can use negative nice values."
+		echo "* Using nice level "$NICE", only root can use negative nice values."
 	else 
-		echo "Using nice level "$NICE"."
+		echo "* Using nice level "$NICE"."
 	fi
-	echo " "
 	/bb/renice -n "$NICE" -p $$
 fi
+
 
 # Determine if non-interactive mode is being used.
 if grep -i "^NONINTERACTIVE=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
@@ -91,34 +87,64 @@ fi
 shift `expr $OPTIND - 1`
 UPDATETARGET=`basename "$1" .sce`
 OPTIONS=""
+
+if [ "$UPDATEALL" == "TRUE" ]; then
+	if [ -n "$1" ]; then
+		echo " "
+		echo "${YELLOW}Warning:${NORMAL} The -a option is not to be used with a specified SCE, exiting.."
+		exit 1
+	else
+		echo "* Using the -a option."
+	fi
+fi
+
+if [ "$SCEBOOTLIST" == "TRUE" ]; then
+	if [ -n "$1" ]; then
+		echo " "
+		echo "${YELLOW}Warning:${NORMAL} The -b option is not to be used with a specified SCE, exiting.."
+		exit 1
+	else
+		echo "* Using the -b option."
+	fi
+fi
+
+if [ "$CHECKONLY" == "TRUE" ]; then
+	echo "* Using the -c option."
+fi
+
+if [ "$NONINTERACTIVE" == "TRUE" ]; then
+	echo "* Using the -n option."
+fi
+
 if [ "$RAM" == "TRUE" ]; then
+	echo "* Using the -r option."
 	OPTIONS=""$OPTIONS"r"
 fi
 
 if [ "$SIZE" == "TRUE" ]; then
+	echo "* Using the -s option."
 	OPTIONS=""$OPTIONS"s"
+fi
+
+if [ "$NOCONFIG" == "TRUE" ]; then
+	echo "* Using the -z option."
 fi
 
 if [ -z "$1" ] && [ "$SCEBOOTLIST" != "TRUE" ]; then
 	SELECT=TRUE
 fi
 
-if [ "$SCEBOOTLIST" == "TRUE" ]; then
-	if [ -n "$1" ]; then
-		echo "The -b option is not to be used with a specified SCE, exiting.."
-		exit 1
-	fi
-fi
-
 if [ "$SCEBOOTLIST" == "TRUE" ] && [ "$UPDATEALL" == "TRUE" ]; then
-	echo "The -a and -b options cannot be used together, exiting.."
+	echo " "
+	echo "${YELLOW}Warning:${NORMAL} The -a and -b options cannot be used together, exiting.."
 	exit 1
 fi
 
 if [ -n "$2" ]; then
-     echo "Only one SCE per sce-update session can be entered in command line."
-     echo "Run 'sce-update' to check more than one SCE per session, exiting.."
-     exit 1
+	echo " "
+	echo "${YELLOW}Warning:${NORMAL} Only one SCE per sce-update session can be entered in command line."
+	echo "         Run 'sce-update' to check more than one SCE per session, exiting.."
+	exit 1
 fi
 
 [ -d /tmp/work ] && sudo rm -r /tmp/work
@@ -158,7 +184,7 @@ cd /etc/sysconfig/tcedir/sce
 
 exit_tcnet() {
 	echo " "
-	echo "There is an issue connecting to `cat /opt/tcemirror`, exiting.."
+	echo "${YELLOW}Warning:${NORMAL} Issue connecting to `cat /opt/tcemirror`, exiting.."
 	exit 1
 }
 
@@ -170,7 +196,7 @@ IMPORTMIRROR="${IMPORTMIRROR%/}/dCore/import"
 sudo debGetEnv "$2"
 if [ "$?" != "0" ]; then
 	echo " "
-	echo "Error updating DEBINX files, exiting.."
+	echo "${YELLOW}Warning:${NORMAL} Error updating DEBINX files, exiting.."
 	exit 1
 fi
 read DEBINX < /etc/sysconfig/tcedir/import/debinx/debinx
@@ -207,14 +233,15 @@ if [ "$UPDATEALL" == "TRUE" ]; then
 	MDNEW=`md5sum NEWDEBINX | cut -f1 -d" "`
 	if [ "$MDOLD" == "$MDNEW" ]; then
 		echo " "
-		echo "The entire SCE directory is up to date."
+		echo "The entire SCE directory is up to date, exiting.."
 		sudo rm NEWDEBINX
 		exit 0
 	elif [ ! "$NONINTERACTIVE" == "TRUE" ]; then
 		echo " "
 		if [ ! -f "$DEBINXDIR"/OLDDEBINX ]; then
-			echo "No "$DEBINXDIR"/OLDDEBINX available for comparison,"
-			echo -n "recommend press Enter to proceed with update check, Ctrl-C aborts: "
+			echo "${YELLOW}Warning:${NORMAL} No "$DEBINXDIR"/OLDDEBINX available to compare."
+			echo " "
+			echo -n "Recommend press Enter to proceed with update check, Ctrl-C aborts: "
 			read ans
 			echo " "
 			:
@@ -224,9 +251,9 @@ if [ "$UPDATEALL" == "TRUE" ]; then
 			read ans
 			echo " "
 			if [ "$ans" == "v" ] || [ "$ans" == "V" ]; then
-				echo "Obtaining diff of new and old package data..."
-				echo " "
+				echo -n "Obtaining diff of new and old package data."
 				diff "$DEBINXDIR"/OLDDEBINX "$DEBINXDIR"/NEWDEBINX > /dev/null 2>&1 > /tmp/debinx.diff & /usr/bin/rotdash $!
+				echo " " && echo " "
 				more -s /tmp/debinx.diff
 				rm /tmp/debinx.diff
 				echo " "
@@ -262,8 +289,9 @@ if [ "$UPDATEALL" == "TRUE" ]; then
 				continue
 			fi
 		fi
-		echo "         ${YELLOW}"$I".sce${NORMAL} update check..."
+		echo -n "         ${YELLOW}"$I".sce${NORMAL} update check."
 		importupdatecheck "$I" > /dev/null 2>&1 & /usr/bin/rotdash $!
+		echo " "
 	done
 	if [ -s /tmp/.sceupdatelist ]; then
 		if [ "$CHECKONLY" != "TRUE" ]; then
@@ -290,7 +318,7 @@ if [ "$UPDATEALL" == "TRUE" ]; then
 				echo " "
 				cat  /tmp/.sceupdatelist | sort | uniq
 				echo " "
-                                echo -n "Press Enter to update above SCE(s), (v)iew package update details, Ctrl-C aborts: "
+                                echo -n "Press Enter to update above SCE(s), (v)iew package updates, Ctrl-C aborts: "
 				read ans
 				echo " "
 				if [ "$ans" == "v" ] || [ "$ans" == "V" ]; then
@@ -323,7 +351,7 @@ if [ "$UPDATEALL" == "TRUE" ]; then
 			echo " "
 			cat  /tmp/.sceupdatelist | sort | uniq
 			echo " "
-			echo -n "Press Enter to view package update details, Ctrl-C aborts: "
+			echo -n "Press Enter to view package updates, Ctrl-C aborts: "
 			read ans
 			if [ "$ans" == "" ] || [ "$ans" == "v" ] || [ "$ans" == "V" ]; then
 				more -s /tmp/updateavailable
@@ -339,10 +367,12 @@ if [ "$UPDATEALL" == "TRUE" ]; then
 	##
 elif [ "$SCEBOOTLIST" == "TRUE" ]; then
 	echo " "
-	if [ -n "$1" ]; then
-		echo "The -b option is not to be used with a specified SCE, exiting.."
-		exit 1
-	fi	
+	## Added top of script:
+	#if [ -n "$1" ]; then
+	#	echo " "
+	#	echo "${YELLOW}Warning:${NORMAL} The -b option is not to be used with a specified SCE, exiting.."
+	#	exit 1
+	#fi	
 	for i in `cat /proc/cmdline`; do
 		case $i in
 			lst=*) TARGETLIST=${i#*=} ;;
@@ -368,8 +398,9 @@ elif [ "$SCEBOOTLIST" == "TRUE" ]; then
 				continue
 			fi
 		fi
-		echo "         ${YELLOW}"$I".sce${NORMAL} update check..."
+		echo -n "         ${YELLOW}"$I".sce${NORMAL} update check."
 		importupdatecheck "$I" > /dev/null 2>&1 & /usr/bin/rotdash $!
+		echo " "
 	done
 	if [ -s /tmp/.sceupdatelist ]; then
 		if [ "$CHECKONLY" != "TRUE" ]; then
@@ -453,24 +484,23 @@ elif [ "$SELECT" == "TRUE" ]; then
 		sed -i "/^$ANS$/d" /tmp/.scelistchoose
 	done
 	##
-	echo " "
 	if [ ! -s /tmp/.sceupdatechoose ]; then
-		echo " "
-		echo "No SCEs chosen for update check, exiting.."
+		echo "No SCE(s) chosen for update check, exiting.."
 		exit 0
 	fi
+	echo " "
 	cat /tmp/.sceupdatechoose | tr -d :
 	echo " "
 	echo -n "Press Enter to update check above SCE(s), (q)uit to exit: "
 	read ANS
-	echo " "
 	if [ "$ANS" == "q" ] || [ "$ANS" == "Q" ]; then
 		cleanup
 		exit 0
 	else
 		## Update selected SCEs
+		echo " "
 		for D in `cat /tmp/.sceupdatechoose | tr -d :`; do
-			echo "Checking ${YELLOW}"$D".sce${NORMAL}..."
+			echo "Checking ${YELLOW}"$D".sce${NORMAL}."
 			unset DEPLIST
 			getDeps "$D"
 			for I in `echo "$DEPLIST"`; do
@@ -480,7 +510,7 @@ elif [ "$SELECT" == "TRUE" ]; then
 					MDOLD=`cat update/"$I".sce.debinx`
 					if [ "$MDOLD" == "$MDNEW" ]; then
 						echo "         ${YELLOW}"$I".sce${NORMAL} is up to date."
-							continue
+						continue
 					fi
 				elif [ -f "$I".sce.debinx ] && [ -f "$I".sce.md5.txt ]; then
 					MDNEW=`md5sum /etc/sysconfig/tcedir/import/debinx/NEWDEBINX | cut -f1 -d" "`
@@ -490,8 +520,9 @@ elif [ "$SELECT" == "TRUE" ]; then
 						continue
 					fi
 				fi
-				echo "         ${YELLOW}"$I".sce${NORMAL} update check..."
+				echo -n "         ${YELLOW}"$I".sce${NORMAL} update check."
 				importupdatecheck "$I" > /dev/null 2>&1 & /usr/bin/rotdash $!
+				echo " "
 			done
 		done
 		if [ -s /tmp/.sceupdatelist ]; then
@@ -570,7 +601,7 @@ elif [ "$SELECT" == "TRUE" ]; then
 		else
 			if [ "$VIEWED" != "TRUE" ]; then
 				echo " "
-				echo -n "Press Enter to review packages that had updates available, (n)o to exit: "
+				echo -n "Press Enter to review available updates, (n)o to exit: "
 				read ans
 				if [ "$ans" == "" ]; then
 					more -s /tmp/updateavailable
@@ -581,7 +612,7 @@ elif [ "$SELECT" == "TRUE" ]; then
 
 elif [ -f update/"$UPDATETARGET".sce ]; then
 	cd update/
-	echo "Searching for available updates for "$UPDATETARGET".sce."
+	echo "Checking ${YELLOW}"$UPDATETARGET".sce${NORMAL} for updates."
 	unset DEPLIST
 	getDeps "$UPDATETARGET"
 	for I in `echo "$DEPLIST"`; do
@@ -600,8 +631,9 @@ elif [ -f update/"$UPDATETARGET".sce ]; then
 				continue
 			fi
 		fi
-		echo "         ${YELLOW}"$I".sce${NORMAL} update check..."
+		echo -n "         ${YELLOW}"$I".sce${NORMAL} update check."
 		importupdatecheck "$I" > /dev/null 2>&1 & /usr/bin/rotdash $!
+		echo " "
 	done
 	if [ -s /tmp/.sceupdatelist ]; then
 		if [ "$CHECKONLY" != "TRUE" ]; then
@@ -675,7 +707,7 @@ elif [ -f update/"$UPDATETARGET".sce ]; then
 	cd ..
 elif [ -f "$UPDATETARGET".sce ]; then
 	echo " "
-	echo "Searching for available updates for ${YELLOW}"$UPDATETARGET".sce${NORMAL}."
+	echo "Checking ${YELLOW}"$UPDATETARGET".sce${NORMAL} for updates."
 	unset DEPLIST
 	getDeps "$UPDATETARGET"
 	for I in `echo "$DEPLIST"`; do
@@ -694,8 +726,9 @@ elif [ -f "$UPDATETARGET".sce ]; then
 				continue
 			fi
 		fi
-		echo "         ${YELLOW}"$I".sce${NORMAL} update check..."
+		echo -n "         ${YELLOW}"$I".sce${NORMAL} update check."
 		importupdatecheck "$I" > /dev/null 2>&1 & /usr/bin/rotdash $!
+		echo " "
 	done
 	if [ -s /tmp/.sceupdatelist ]; then
 		if [ "$CHECKONLY" != "TRUE" ]; then
@@ -764,7 +797,7 @@ elif [ -f "$UPDATETARGET".sce ]; then
 	fi
 else
 	echo " "
-	echo ""$UPDATETARGET" is not an existing SCE file, exiting.."
+	echo "${YELLOW}Warning:${NORMAL} '"$UPDATETARGET"' is not an existing SCE file, exiting.."
 fi
 
 cleanup
@@ -780,4 +813,3 @@ fi
 if ls /tmp/*.deb2sce > /dev/null 2>&1; then
 	sudo rm /tmp/*.deb2sce
 fi
-
