Help menu and other enhances provided my nitram.

diff --git a/usr/bin/sce-debpurge b/usr/bin/sce-debpurge
--- a/usr/bin/sce-debpurge
+++ b/usr/bin/sce-debpurge
@@ -17,15 +17,23 @@ fi
 
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
 	echo
-	echo "sce-debpurge - purge deprecated local DEB files."
+	echo "${YELLOW}sce-debpurge - purge deprecated DEB files or all files from /etc/"
+        echo "               sysconfig/tcedir/import/debs.${NORMAL}"
 	echo
 	echo "Usage:"
 	echo
-	echo -e "'"sce-debpurge"'    without options update DEBINX package index, purge deprecated \n                  debs from import directory."
-	echo -e "'"sce-debpurge -p"' do not update DEBINX package index, purge deprecated debs \n                  based on current index."
+	echo "${YELLOW}'"sce-debpurge"'${NORMAL}     update DEBINX files (Debian Index files located in /etc/"
+        echo "                   sysconfig/tcedir/import/debinx), purge deprecated DEBs."
+	echo "${YELLOW}'"sce-debpurge -p"'${NORMAL}  preserve local DEBINX files, purge deprecated DEBs"
+        echo "                   based on current index."
+	echo "${YELLOW}'"sce-debpurge -a"'${NORMAL}  purge all files from /etc/sysconfig/tcedir/import/debs,"
+        echo "                   including *.deb and *.tar.gz, note purged files will"
+        echo "                   need to be re-downloaded to rebuild SCEs during"
+        echo "                   updates or re-imports."
 	echo
 exit 1
 fi
+
 
 read IMPORTMIRROR < /opt/tcemirror
 PREBUILTMIRROR="${IMPORTMIRROR%/}/dCore/"$BUILD"/import"
@@ -38,7 +46,8 @@ do
 	case ${OPTION} in
 		p) PRESERVEDEBINXMODE=TRUE ;;
 		a) PURGEALL=TRUE ;;
-		*) exit 1 ;;
+		*) echo "Run  sce-debpurge --help  for usage information."
+                   exit 1 ;;
 	esac
 done
 
@@ -52,11 +61,15 @@ else
 fi
 
 if [ "$PURGEALL" == "TRUE" ]; then
-	cd /etc/sysconfig/tcedir/import/debs
+        echo
+        echo "Purging all files from /etc/sysconfig/tcedir/import/debs.."
+	echo
+        cd /etc/sysconfig/tcedir/import/debs
 	if ls *.deb > /dev/null 2>&1; then
 		for I in `ls *.deb`; do
 			ls -l "$I" | cut -f5 -d" " >> /tmp/.debpurgedsize
 			echo "Removing "$I".."
+                        echo
 			sudo rm "$I"
 			echo "$I" >> /tmp/.debpurged
 		done
@@ -65,15 +78,21 @@ if [ "$PURGEALL" == "TRUE" ]; then
 		for I in `ls *.tar.gz`; do
 			ls -l "$I" | cut -f5 -d" " >> /tmp/.debpurgedsize
 			echo "Removing "$I".."
+                        echo
 			sudo rm "$I"
 			echo "$I" >> /tmp/.debpurged
 		done
 	fi
-	echo "All packages removed from /etc/sysconfig/tcedir/import/debs." 
+        echo
+	echo "All packages removed from /etc/sysconfig/tcedir/import/debs."
 	DPURGESIZEFINAL=$(echo `awk 'BEGIN{total=0};{total += $1};END{print total/1024/1024}' /tmp/.debpurgedsize` | awk '{printf("%.2f\n", $1)}')
+        echo
 	echo "Total space freed by removing unneeded files:  "$DPURGESIZEFINAL" MB"
 	exit 0
 fi
+
+
+
 		
 
 exit_tcnet() {
@@ -140,10 +159,13 @@ getName1() {
 > /tmp/.debpurged
 
 if [ "$PRESERVEDEBINXMODE" != "TRUE" ]; then
-	cd /tmp
-	sudo debGetEnv 
+        echo
+        echo "Fetching updated DEBINX, checking for deprecated DEB files.."
+	echo
+        cd /tmp
+	sudo debGetEnv
 	if [ "$?" != "0" ]; then
-		echo "Error in updating needed DEBINX files.  Exiting..."
+		echo "Error in updating needed DEBINX files, exiting.."
 		exit 1
 	fi
 	wget -O deb2sce.tar.gz -cq "$PREBUILTMIRROR"/deb2sce.tar.gz 2>/dev/null ||  exit_tcnet
@@ -156,6 +178,11 @@ if [ "$PRESERVEDEBINXMODE" != "TRUE" ]; then
 	tar xvf /tmp/deb2sce.tar.gz PKGEXTRAFILEMD5SUMLIST >/dev/null 2>&1
 	tar xvf /tmp/deb2sce.tar.gz PKGDATAFILEMD5SUMLIST >/dev/null 2>&1
 	tar xvf /tmp/deb2sce.tar.gz PREBUILTMD5SUMLIST >/dev/null 2>&1
+fi
+
+if [ "$PRESERVEDEBINXMODE" = "TRUE" ]; then
+       echo
+       echo "Preserving local DEBINX, checking for deprecated DEB files.."
 fi
 
 cd /etc/sysconfig/tcedir/import/debs
@@ -242,9 +269,12 @@ if ls *.tar.gz > /dev/null 2>&1; then
  done
 fi
 
-echo "All non current packages removed from /etc/sysconfig/tcedir/import/debs." 
+echo
+echo "All non current packages removed from /etc/sysconfig/tcedir/import/debs."
 DPURGESIZEFINAL=$(echo `awk 'BEGIN{total=0};{total += $1};END{print total/1024/1024}' /tmp/.debpurgedsize` | awk '{printf("%.2f\n", $1)}')
+echo
 echo "Total space freed by removing unneeded files:  "$DPURGESIZEFINAL" MB"
+echo
 exit 0
 
 
diff --git a/usr/bin/sce-update b/usr/bin/sce-update
--- a/usr/bin/sce-update
+++ b/usr/bin/sce-update
@@ -9,18 +9,21 @@ BUILD=`getBuild`
 unset DEPLIST
 if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
 	echo
-	echo "sce-update - check for updates and/or update SCEs."
+	echo "${YELLOW}sce-update - check for updates and update SCE(s).${NORMAL}"
 	echo
 	echo "Usage:"
 	echo
-	echo "'"sce-update"'    without options brings up menu of SCEs to choose to update."
-	echo "'"sce-update -a"' updates all existing SCEs, both loaded and unloaded."
-	echo "'"sce-update -n"' non-interactive mode."
-	echo "'"sce-update -c"' check only 'dry run' mode, no option to update."
-	echo "'"sce-update -r"' sce-import unpacks files in RAM during update."
-	echo "'"sce-update -s"' sce-import checks for size and available space during update."
-	echo -e "'"sce-update -z"' ignore /etc/sysconfig/sceconfig, use only current command \n                line options."
-	echo "'"sce-update iceweasel"' update Iceweasel."
+	echo "${YELLOW}'"sce-update"'${NORMAL}      menu prompt, choose SCE(s) to check, update if required."
+       	echo "${YELLOW}'"sce-update SCE"'${NORMAL}  check specific SCE for updates, update if required."
+	echo "${YELLOW}'"sce-update -a"'${NORMAL}   check all SCEs for updates, both loaded and unloaded,"
+        echo "                  update if required."
+	echo "${YELLOW}'"sce-update -n"'${NORMAL}   non-interactive mode."
+	echo "${YELLOW}'"sce-update -c"'${NORMAL}   menu prompt, check selected SCE(s) for updates,"
+        echo "                  no actual updates performed."
+	echo "${YELLOW}'"sce-update -r"'${NORMAL}   sce-import unpacks files in RAM during update."
+	echo "${YELLOW}'"sce-update -s"'${NORMAL}   sce-import checks for size, available space during update."
+	echo "${YELLOW}'"sce-update -z"'${NORMAL}   ignore /etc/sysconfig/sceconfig, use only current"
+        echo "                  command line options."
 	echo
 	exit 0
 fi
@@ -34,8 +37,12 @@ do
 		a) UPDATEALL=TRUE ;;
 		s) SIZE=TRUE ;;
 		z) NOCONFIG=TRUE ;;
+                *) echo "Run  sce-update --help  for usage information."
+                   exit 1 ;;
 	esac
 done
+
+
 
 # Determine if non-interactive mode is being used.
 if grep -i "^NONINTERACTIVE=TRUE" /etc/sysconfig/sceconfig > /dev/null 2>&1 && [ "$NOCONFIG" != "TRUE" ]; then
