debGetEnv,sce-import,sce-update: Bugfixes.

diff --git a/usr/bin/sce-import b/usr/bin/sce-import
--- a/usr/bin/sce-import
+++ b/usr/bin/sce-import
@@ -256,8 +256,14 @@ fi
 
 if [ "$UPDATEDEBINXMODE" == "TRUE" ]; then
 	sudo debGetEnv "$2"
+	if [ "$?" != "0" ]; then
+		echo "Error in updating DEBINX files.  Exiting..."
+	fi
 else
 	[ -s /tmp/debinx ] || sudo debGetEnv "$2"
+	if [ "$?" != "0" ]; then
+		echo "Error in updating DEBINX files.  Exiting..."
+	fi
 fi
 
 read DEBINX < /tmp/debinx
diff --git a/usr/bin/sce-update b/usr/bin/sce-update
--- a/usr/bin/sce-update
+++ b/usr/bin/sce-update
@@ -58,6 +58,9 @@ PREBUILTMIRROR="${IMPORTMIRROR%/}/dCore/"$BUILD"/import"
 IMPORTMIRROR="${IMPORTMIRROR%/}/dCore/import"
 
 sudo debGetEnv "$2"
+if [ "$?" != "0" ]; then
+	echo "Error in updating needed DEBINX files.  Exiting..."
+fi
 read DEBINX < /tmp/debinx
 cd /tmp
 
